require('plugins.config.lualine')
require('plugins.config.lsp_zero')
require('plugins.config.registers')
require('plugins.config.telescope')
require('plugins.config.neo-tree')
require('plugins.config.gitsigns')
require('plugins.config.fidget')
