# ~/.config/starship.toml

format="""
$username\
$hostname\
${custom.pwd}\
$git_branch\
$git_commit\
$git_state\
$line_break\
$character"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false

[git_branch]
always_show_remote = true
format = "[$branch ]($style)[($remote_name/$remote_branch )](bold red)"

[git_commit]
commit_hash_length = 12
only_detached = false
tag_disabled = false


[custom.pwd]
command = "smart-pwd"
when = true
